# Generated by Django 4.1.2 on 2022-12-17 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0002_locations_securityquestions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='padron',
            old_name='email',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='padron',
            old_name='estate',
            new_name='state',
        ),
        migrations.RenameModel(
            old_name='Locations',
            new_name='States',
        ),
        migrations.CreateModel(
            name='Towns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=3)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='census.states')),
            ],
        ),
    ]
