# Generated by Django 4.1.2 on 2022-12-17 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0003_rename_email_padron_mail_rename_estate_padron_state_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SecurityQuestions',
            new_name='SecurityQuestion',
        ),
        migrations.RenameModel(
            old_name='States',
            new_name='State',
        ),
        migrations.RenameModel(
            old_name='Towns',
            new_name='Town',
        ),
    ]
