# Generated by Django 4.1.2 on 2022-12-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0003_remove_locations_towns'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='code',
            field=models.CharField(default='001', max_length=3),
            preserve_default=False,
        ),
    ]
