# Generated by Django 4.1.2 on 2022-12-17 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0004_rename_securityquestions_securityquestion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='padron',
            old_name='secQuest1',
            new_name='secQuestion1',
        ),
        migrations.RenameField(
            model_name='padron',
            old_name='secQuest2',
            new_name='secQuestion2',
        ),
        migrations.RenameField(
            model_name='padron',
            old_name='secQuest3',
            new_name='secQuestion3',
        ),
    ]
