# Generated by Django 4.1.2 on 2022-12-13 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0004_locations_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locations',
            old_name='states',
            new_name='state',
        ),
    ]
