# Generated by Django 4.1.4 on 2022-12-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0005_rename_secquest1_padron_secquestion1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='town',
            name='code',
            field=models.CharField(max_length=4),
        ),
    ]
