# Generated by Django 4.1.2 on 2022-12-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0006_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstName',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(default='h', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='memberID',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
