# Generated by Django 4.1.2 on 2022-12-13 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0007_user_firstname_user_lastname_user_memberid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
