# Generated by Django 4.1.2 on 2022-12-13 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0008_rename_user_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
